### ISSUE TITLE
x-axe overflow on 13"

### ISSUE THREAD

**Issue by zoepage** [emceeaich/are-we-triaged-yet#59]
STR:
1. open https://are-we-triaged-yet.glitch.me/ with a window width < 1440px

EB:
- Site fits the width of the screen.

AB:
- The x-axe is scroll-able.

Due to https://github.com/w3c/csswg-drafts/issues/1766 the scrollbar is calculated in the viewport, which is causing an overflow on the x-axe.

https://github.com/emceeaich/are-we-triaged-yet/blob/master/public/style.css#L10
This can be fixed for some win / linux by changing the `width: 100vw`  to `width: 100%`.

There is also the issue of the grid is getting sized against the padding box of the `body`, which is what causes the weirdness for the other use case.

I'm running OSX 10.13.3, FF 64 latest build (also happens on Chrome 69) with a 13" display (width: 1440px).

@matspalmgren Maybe you have an idea why this happens?

**Comment by emceeaich** [comment]
Partial fix merged into master, will be part of v2 release

**Comment by MatsPalmgren** [comment]
Adding this rule might help: body > div { min-width:0; }
